import type { Metadata } from 'next';
import './globals.css';
import { Suspense } from 'react';

import { auth } from '@/configs/auth-option';
import { Loading } from '@components/core/commons/loading';
import Scroll from '@components/core/commons/scroll';
import { AppProviders } from '@components/core/providers/app-provider';
import { cn } from '@lib/utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html suppressHydrationWarning lang="vi">
      <body className={cn()}>
        <Suspense fallback={<Loading />}>
          <Scroll />
          <AppProviders session={session ?? undefined}>{children}</AppProviders>
        </Suspense>
      </body>
    </html>
  );
}
