import type { Metadata } from 'next';
import './globals.css';
import { Suspense } from 'react';

import { Loading } from '@components/core/commons/loading';
import Scroll from '@components/core/commons/scroll';
import { AppProviders } from '@components/core/providers/app-provider';
import { cn } from '@lib/utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="vi">
      <body className={cn()}>
        <Suspense fallback={<Loading />}>
          <Scroll />
          <AppProviders>{children}</AppProviders>
        </Suspense>
      </body>
    </html>
  );
}
